import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';

type Data = {
  id: number,
  area: number,
}

export default function Home() {
  const [data, setData] = useState<Data[]>([]);
  const query = useRouter()

  const hasArea = (id: number) => {
    let has = false;
    
    data.map((value) => {
      if (value.area === id) {
        has = true;
      }
    });

    return has;
  }

  const accessAreaScreen = (id: number) => {
    if(hasArea(id)) {
      query.replace(`/area/${id}`);
    }
  }

  useEffect(() => {
    fetch(`http://localhost:3000/api/alocacoes`).then((res) => res.json()).then((data) => setData(data));
  }, []);

  return (
    <div className='h-full w-full'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='w-full h-4 bg-[#707070]'>
      </div>
      <div className='bg-[#707070] m-auto mt-16 h-[700px] w-[1000px] relative scale-[0.90]'>
        <div onClick={() => accessAreaScreen(1)} className={`flex items-center justify-center border-2 ${hasArea(1) ? 'bg-[#0000ff] cursor-pointer' : 'bg-white'} border-black border-solid absolute h-48 w-48 z-10 bottom-36`} id="1">1</div>
        <div onClick={() => accessAreaScreen(2)} className={`flex items-center justify-center border-2 ${hasArea(2) ? 'bg-[#0000ff] cursor-pointer' : 'bg-white'} border-black border-solid absolute h-20 w-16 left-[270px] z-[11] bottom-[210px]`} id="2">2</div>
        <div onClick={() => accessAreaScreen(3)} className={`flex items-center justify-center border-2 ${hasArea(3) ? 'bg-[#0000ff] cursor-pointer' : 'bg-white'} border-black border-solid absolute h-80 w-64 left-24 z-[9] bottom-[-10px]`} id="3">3</div>
        <div onClick={() => accessAreaScreen(4)} className={`flex items-center justify-center border-2 ${hasArea(4) ? 'bg-[#0000ff] cursor-pointer' : 'bg-white'} border-black border-solid absolute h-20 w-32 left-[184px] z-50 bottom-[295px]`} id="4">4</div>
        <div onClick={() => accessAreaScreen(5)} className={`flex items-center justify-center border-2 ${hasArea(5) ? 'bg-[#0000ff] cursor-pointer' : 'bg-white'} border-black border-solid absolute h-[350px] w-[350px] left-72 z-[8] bottom-[-10px]`} id="5">5</div>
        <div onClick={() => accessAreaScreen(6)} className={`flex items-center justify-center border-2 ${hasArea(6) ? 'bg-[#0000ff] cursor-pointer' : 'bg-white'} border-black border-solid absolute h-12 w-32 z-[12] top-[-5px] right-16`} id="6">6</div>
        <div onClick={() => accessAreaScreen(7)} className={`flex items-center justify-center border-2 ${hasArea(7) ? 'bg-[#0000ff] cursor-pointer' : 'bg-white'} border-black border-solid absolute h-14 w-28 left-[312px] bottom-[340px] z-[60]`} id="7">7</div>
        <div onClick={() => accessAreaScreen(8)} className={`flex items-center justify-center border-2 ${hasArea(8) ? 'bg-[#0000ff] cursor-pointer' : 'bg-white'} border-black border-solid absolute h-12 w-24 left-[315px] top-[105px]`} id="8">8</div>
        <div onClick={() => accessAreaScreen(9)} className={`flex items-center justify-center border-2 ${hasArea(9) ? 'bg-[#0000ff] cursor-pointer' : 'bg-white'} border-black border-solid absolute h-14 w-28 left-[410px] top-[100px]`} id="9">9</div>
        <div onClick={() => accessAreaScreen(10)} className={`flex items-center justify-center border-2 ${hasArea(10) ? 'bg-[#0000ff] cursor-pointer' : 'bg-white'} border-black border-solid absolute h-[670px] w-[350px] top-[-5px] right-16`} id="10">10</div>
        <div onClick={() => accessAreaScreen(11)} className={`flex items-center justify-center border-2 ${hasArea(11) ? 'bg-[#0000ff] cursor-pointer' : 'bg-white'} border-black border-solid absolute h-[70px] w-[55px] top-7 left-96`} id="10">11</div>
      </div>
    </div>
  )
}
